version: '3.7'

networks:
  laravel:

services:
  app:
    container_name: 'leben-app'
    build:
      args:
        user: fadlur
        uid: 1000
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./api:/var/www
    networks:
      - laravel

  mysql:
    container_name: 'leben-mysql'
    platform: linux/x86_64/v8
    image: mysql/mysql-server:8.0.23
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - laravel
    environment:
      MYSQL_DATABASE: leben
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: admin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
  nginx:
    container_name: 'leben-nginx'
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'leben-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      UPLOAD_LIMIT: 512M
      MEMORY_LIMIT: 512M
    ports:
      - '8899:80'
    volumes:
      - /sessions
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    networks:
      - laravel
